### ISSUE TITLE
Error thrown when no data. Should be a warning

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#163]
When there is no data, one might except a warning, not an error. 
And when asked for a plot, this one should be returned as empty, not with a fatal error.

![image](https://user-images.githubusercontent.com/6871008/178120515-1f4359a5-cd3d-4653-a6d7-60e957f519fc.png)

**Comment by odadoun** [comment]
partially fixed for plot and hist not yet for map

**Comment by odadoun** [comment]
done for map also

**Comment by tjbtjbtjb** [comment]
It works. But not when `bypop` activated. 

![image](https://user-images.githubusercontent.com/6871008/178148092-54397ac4-6f0d-4e54-bde4-64f6ee92b5e1.png)

**Comment by odadoun** [comment]
bypop pb fixed

**Comment by tjbtjbtjb** [comment]
It still does not work with `hist` (`byvalue`, `bycountry` or `pie`) unfortunately…

![image](https://user-images.githubusercontent.com/6871008/178257674-b2fc36e0-7567-4b18-9bf6-f13a078c5449.png)

**Comment by odadoun** [comment]
fixed !
